import os

FRONTEND_URL = os.getenv("VITE_API_URL")

# TEST OR DEV
DEV = os.getenv("DEV") == "TRUE"

# STORAGE / R2 CONFIGURATION

R2_ENDPOINT = os.environ["S3_API"]
R2_ACCESS_KEY = os.environ["CLOUDFLARE_R2_ACCESS_KEY"]
R2_SECRET_KEY = os.environ["CLOUDFLARE_R2_SECRET_ACCESS_KEY"]

R2_BUCKET = "trueswing-videos"

FFMPEG_DEFAULT_TIMESTAMP = 1.5
THUMBNAIL_BASE_PREFIX = "golf-thumbnails"
THUMBNAIL_FILENAME = "thumbnail.webp"


# AI CONFIGURATION
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# DATABASE CONFIGURATION


# SUPABASE CONFIGURATION
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLL_KEY = os.getenv("SUPABASE_SERVICE_ROLL_KEY")

# Stripe
STRIPE_SECRET_KEY = os.getenv("SANDBOX_STRIPE_SECRET_KEY") if DEV else os.getenv("LIVE_STRIPE_SECRET_KEY")
STRIPE_PUBLISH_KEY = os.getenv("SANDBOX_STRIPE_PUBLISH_KEY") if DEV else os.getenv("LIVE_STRIPE_PUBLISH_KEY")
PRICE_ID = os.getenv("SANDBOX_STRIPE_PRICE_ID") if DEV else os.getenv("LIVE_STRIPE_PRICE_ID")
STRIPE_WEBHOOK_SECRET = os.getenv("whsec_a29a0f0fa28e0a154334ca72cb7c63678b34f4e7ca3ee569472c8c4bde9245e6")