services:
  # --- Backend: Flask API ---
  - type: web
    name: flask-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app --timeout 120 --keep-alive 5
    healthCheckPath: /ping
    previews:
      generation: automatic
    buildFilter:
      paths:
        - backend/**

  # --- Frontend: Vite (static site) ---
  - type: web
    name: react-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: flask-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    previews:
      generation: automatic
    buildFilter:
      paths:
        - frontend/**
