/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/browse` | `/add-focus/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/coach` | `/add-focus/coach`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/upload` | `/add-focus/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(drawer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/add-focus/browse` | `/add-focus/browse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/add-focus/coach` | `/add-focus/coach`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/add-focus/upload` | `/add-focus/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(drawer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/add-focus/browse${`?${string}` | `#${string}` | ''}` | `/add-focus/browse${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/add-focus/coach${`?${string}` | `#${string}` | ''}` | `/add-focus/coach${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/add-focus/upload${`?${string}` | `#${string}` | ''}` | `/add-focus/upload${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/browse` | `/add-focus/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/coach` | `/add-focus/coach`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-focus/upload` | `/add-focus/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; };
    }
  }
}
